# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/miguel/Desktop/NOVOpsd/NOVOpsd.cache/wt [current_project]
set_property parent.project_path /home/miguel/Desktop/NOVOpsd/NOVOpsd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/miguel/Desktop/NOVOpsd/NOVOpsd.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/miguel/Desktop/NOVOpsd/NOVOpsd.srcs/sources_1/imports/P3/datapath.vhd
  /home/miguel/Desktop/NOVOpsd/NOVOpsd.srcs/sources_1/imports/P3/control.vhd
  /home/miguel/Desktop/NOVOpsd/NOVOpsd.srcs/sources_1/imports/P3/circuit.vhdl
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top circuit -part xc7a35tcpg236-1


write_checkpoint -force -noxdef circuit.dcp

catch { report_utilization -file circuit_utilization_synth.rpt -pb circuit_utilization_synth.pb }
