# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/miguel/P2/P2.srcs/sources_1/ip/memC/memC.xci
# IP: The module: 'memC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miguel/P2/P2.srcs/sources_1/ip/memC/memC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/miguel/P2/P2.srcs/sources_1/ip/memC/memC.xci
# IP: The module: 'memC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/miguel/P2/P2.srcs/sources_1/ip/memC/memC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
