# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/miguel/Desktop/P3/P3.cache/wt [current_project]
set_property parent.project_path /home/miguel/Desktop/P3/P3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/miguel/Desktop/P3/P3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/PSD_P/P3/datapath.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/PSD_P/P3/control.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/PSD_P/P3/circuit.vhdl
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/PSD_P/P3/top_circuit.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/lab0Files/clkdiv.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/lab0Files/hex2disp.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/lab0Files/disp7.vhd
  /home/miguel/Desktop/P3/P3.srcs/sources_1/imports/PSD_P/P1/project_1.srcs/sources_1/imports/lab0Files/fpga_basicIO.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/miguel/Desktop/P3/P3.srcs/constrs_1/imports/vhdl_P2/Constraints.xdc
set_property used_in_implementation false [get_files /home/miguel/Desktop/P3/P3.srcs/constrs_1/imports/vhdl_P2/Constraints.xdc]


synth_design -top fpga_basicIO -part xc7a35tcpg236-1


write_checkpoint -force -noxdef fpga_basicIO.dcp

catch { report_utilization -file fpga_basicIO_utilization_synth.rpt -pb fpga_basicIO_utilization_synth.pb }
