# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/miguel/P2/P2.cache/wt [current_project]
set_property parent.project_path /home/miguel/P2/P2.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/miguel/P2/P2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci
set_property is_locked true [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/miguel/P2/P2.runs/memRes_synth_1 -new_name memRes -ip [get_ips memRes]]

if { $cached_ip eq {} } {

synth_design -top memRes -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix memRes_ memRes.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ memRes_stub.v
 lappend ipCachedFiles memRes_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ memRes_stub.vhdl
 lappend ipCachedFiles memRes_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ memRes_sim_netlist.v
 lappend ipCachedFiles memRes_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ memRes_sim_netlist.vhdl
 lappend ipCachedFiles memRes_sim_netlist.vhdl

 config_ip_cache -add -dcp memRes.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips memRes]
}

rename_ref -prefix_all memRes_

write_checkpoint -force -noxdef memRes.dcp

catch { report_utilization -file memRes_utilization_synth.rpt -pb memRes_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.v -of_objects [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

add_files /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.vhdl -of_objects [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

add_files /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.v -of_objects [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

add_files /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.vhdl -of_objects [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

add_files /home/miguel/P2/P2.runs/memRes_synth_1/memRes.dcp -of_objects [get_files /home/miguel/P2/P2.srcs/sources_1/ip/memRes/memRes.xci]

if {[file isdir /home/miguel/P2/P2.ip_user_files/ip/memRes]} {
  catch { 
    file copy -force /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.v /home/miguel/P2/P2.ip_user_files/ip/memRes
  }
}

if {[file isdir /home/miguel/P2/P2.ip_user_files/ip/memRes]} {
  catch { 
    file copy -force /home/miguel/P2/P2.runs/memRes_synth_1/memRes_sim_netlist.vhdl /home/miguel/P2/P2.ip_user_files/ip/memRes
  }
}

if {[file isdir /home/miguel/P2/P2.ip_user_files/ip/memRes]} {
  catch { 
    file copy -force /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.v /home/miguel/P2/P2.ip_user_files/ip/memRes
  }
}

if {[file isdir /home/miguel/P2/P2.ip_user_files/ip/memRes]} {
  catch { 
    file copy -force /home/miguel/P2/P2.runs/memRes_synth_1/memRes_stub.vhdl /home/miguel/P2/P2.ip_user_files/ip/memRes
  }
}
